'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class articulos
    Public Property idArticulo As Integer
    Public Property titulo As String
    Public Property texto As String
    Public Property fecha As Date
    Public Property etiquetas As String
    Public Property idAutor As Integer

    Public Overridable Property autores As autores

End Class
Partial Public Class autores
    Public Property idAutor As Integer
    Public Property nombre As String
    Public Property login As String
    Public Property password As String
    Public Property correo As String
    Public Property nacionalidad As String
    Public Property activado As Boolean

    Public Overridable Property articulos As ICollection(Of articulos) = New HashSet(Of articulos)
    Public Overridable Property tags As ICollection(Of tags) = New HashSet(Of tags)

End Class
Partial Public Class tags
    Public Property idTag As Integer
    Public Property tag As String
    Public Property frecuencia As Integer
    Public Property idAutor As Integer

    Public Overridable Property autores As autores

End Class
